### ISSUE TITLE
[Tests] Manganato chapters may have subnumbering which must be skipped

### ISSUE THREAD

**Issue by Joacchim** [BookMyComics-Developers/BookMyComics#105]

**Comment by Joacchim** [comment]
Relates to #108

**Comment by GuillaumeGomez** [comment]
They shouldn't be skipped btw. It's actually quite common.

**Comment by Joacchim** [comment]
With my current experience, I agree, thuogh the issue is the following: Shoudl we expect multiple readers to use similar sub-numbering ?
Similarly, the subnumering takes multiple forms, depending on the comic and reader:
`'XX` then `XX.5`, or sometimes `XX`, then `XX-2`, then `XX-3`, etc.

The difficulty is to know whether/how to use  the "chapter" information on all readers.

**Comment by Joacchim** [comment]
partly supported now, closing. We'll see how it fares
