### ISSUE TITLE
Sidebar: Split Searchbox into two for Registration process: NameInput + Searchbox

### ISSUE THREAD

**Issue by Joacchim** [BookMyComics-Developers/BookMyComics#17]
Although #16 is a very alluring improvement, it also raises the question of whether we want to split the input field into two, to separate the searchbox from the Comic Name input.

Indeed, separating them would allow to search for duplicates with different names, while keeping the pre-filled Comic Name input provided by the web extension.

This is more of a "I wonder" issue than an actual task, but I'll leave it it as food for thoughts.

**Comment by Joacchim** [comment]
@GuillaumeGomez Can we agree it's done since d66a77edfca360c2a21fe2d9414ac63eb946ad4e (where the two scenarios of "Adding a new manga" and "Adding as a source to an existing manga" were separated) ?

**Comment by GuillaumeGomez** [comment]
Yep, #57 did it apparently.
