### ISSUE TITLE
Tests "scenarios"

### ISSUE THREAD

**Issue by GuillaumeGomez** [BookMyComics-Developers/BookMyComics#47]
Scenarios I thought about that we should add:

 * [x] Click on '>' button, check if panel opened
 * [x] Click on '>' button, check if panel opened, click on '<' button, check if tab closed
 * [ ] Click on '>' button, check if panel opened, reload page and check if panel is open
 * [ ] Click on '+' button, check if new menu appeared
 * [ ] Click on '+' button, check if new menu appeared, click on 'cancel', check if panel closed
 * [x] Click on '>' button, check if panel opened, click on '+' button, check if new menu appeared
 * [x] Click on '>' button, check if panel opened, click on '+' button, check if new menu appeared, click on 'cancel' button, check if back to open panel
 * [x] Click on '+' button, add current manga, check if present
 * [ ] Click on '+' button, add current manga, check if present, remove it, check if list is empty
 * [ ] Click on '+' button, add current manga, check if present, add another manga using the same method, check if present, remove the first one, check if only the second one is present
 * [ ] Same as the three above but with the '+' button from the panel instead

**Comment by Joacchim** [comment]
Update:
Points 1 & 2 already done (`tests/func/test_002_sidebar_toggle.py::test_002_sidebar_toggle`)
Point 3: Created issue #99 for this
Point 4 & 5: Created issue #98 for this
Point 6 done (`tests/func/test_100_register.py::test_registration`)
Point 7 done (`tests/func/test_100_register.py::test_registration_cancelled`)
Point 8 done (`tests/func/test_100_register.py::test_registration`)
Point 9: Planned by #41
Point 10: Planned by #41 
Point 11: I believe that once the registration has been tested (cf 4/5), there's no need to use both paths for all scenarii.
