### ISSUE TITLE
[Support][MangaReader] Reader no longer supports HTTPS

### ISSUE THREAD

**Issue by Joacchim** [BookMyComics-Developers/BookMyComics#72]
according to our weekly tests, the mangareader no longer loads the Bmc extension.

After looking a bit into it, I could observe that the extensions requests to match `https://www.mangareader.net/*`, but chrome reports that the connection is insecure.

As such, I suspect that the concerned reader no longer supports HTTPS, and this should be changed in the web-extension manifest.

**Comment by GuillaumeGomez** [comment]
I think we should add a policy to support only manga reader websites with SSL enabled. It's free nowadays to support it so they should use it.

**Comment by Joacchim** [comment]
in which case, with the current supported readers, we'd get down to 2 properly supported websites:
- mangahere.us has a bad certificate (not sure how it'd affect tests if we use https to connect to it), and not recommendable as long as this issue persists
- only mangaeden and fanfox would properly support https.

Also, although I agree with the principle, if we don't support HTTP but only HTTPS, the reader browsing detection would not work when visited in cleartext, which would break what we're attempting to do with this webextension...
Unless the extension forces a redirect to the https version when reaching the supported http website ?

**Comment by Joacchim** [comment]
Temp fix pushed. WE'll need to settle on a long-term solution, and I'll admit to leaning towards forbidding non-secure connections also in the long run, though I don't want to do this before we have enough HTTPS-enabled supported websites

**Comment by Joacchim** [comment]
Dropped since ac897c446e1157bbe837643f6133661373002e90
